global:
 scrape_interval: 5s
 evaluation_interval: 5s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - 172.31.10.2:8080
      - 172.31.20.231:8080
      - 172.31.36.21:8080